### PR TITLE
WIP Attempt to fix subtle bug with Failer.

### PR DESCRIPTION
**Pull request by pathunstrom**

### CODE REVIEW

**Comment by astronouth7303** [comment]
What's the bug?

**Comment by pathunstrom** [comment]
https://ci.appveyor.com/project/astronouth7303/pursuedpybear/builds/23433561/job/t45jlhhpbkl7dapq

Just trying to throw things at the wall with regard to the failure.

**Comment by astronouth7303** [comment]
Did my PR not get merged? _is confused_

**Comment by pathunstrom** [comment]
It did, it's still failing intermittently.

Still Windows, still by a what could be a rounding error.

**Comment by astronouth7303** [comment]
uggggggggggghhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

**Comment by pathunstrom** [comment]
bors try

**Comment by pathunstrom** [comment]
Closing this for now.

**Pull request closed without merging**
