### PR TITLE
Improve flakiness of Failer tests

### PR DESCRIPTION
**Pull request by astronouth7303**
Try to improve the flakiness of the failer timing-based tests.

### CODE REVIEW

**Comment by astronouth7303** [comment]
So, it's still supposed to be within 0.01s of the prescribed time, but I can't reproduce the bug.

Is this version of the test more clear?

**Comment by pathunstrom** [comment]
I preferred the `with raises` but that's not really a problem either way. I like splitting the test in two, nice touch.

The test has been flaky since the beginning, we might have to run the tests a handful of times to guarantee it. (This is that one test that just. . . fails sometimes. Especially on Travis.)

**Comment by astronouth7303** [comment]
I'll rerun them both a few more times, then.

**Comment by astronouth7303** [comment]
Haven't been able to reproduce so far, so yay?

**Comment by pathunstrom** [comment]
Yeah, let's keep this and if it comes back we can approach it again.

**Pull request merged**
