### PR TITLE
Adds CODEOWNERS

### PR DESCRIPTION
**Pull request by pathunstrom**

### CODE REVIEW

**Comment by astronouth7303** [comment]
Does WORKING mean "Work in Progress" or "Please merge"?

**Comment by pathunstrom** [comment]
Work in Progress. I was reading the documentation to make sure I didn't miss anything obvious.

**Comment by nbraud** [comment]
@pathunstrom From the [CODEOWNER documentation], this looks reasonable.
Is there any blocker on merging?

[CODEOWNER documentation]: https://help.github.com/en/articles/about-code-owners

**Comment by nbraud** [comment]
PS: I'd rather have the Github-specific things tucked away under `.github/`, but it's not a strong preference.

**Comment by pathunstrom** [comment]
I thought things like codeowners function on everything in that directory and lower. Did I miss some docs on this?

**Comment by nbraud** [comment]
There's a section on [`CODEOWNERS` file location] in the Github docs.

[`CODEOWNERS` file location]: https://help.github.com/en/articles/about-code-owners#codeowners-file-location

**Pull request merged**
