### PR TITLE
Implement the Game Object Model

### LINKED ISSUE #492: Universal Tree Model/Game Object Model
This is something we've been discussing a long time, but it hasn't had it's own discussion yet.

The idea is to unify the "game object" interface that defines the object tree (engine->systems,scenes->sprites), as well as enable some additional features.

In addition to making tree traversal simpler, some of the additional features I'd like to include:
* Allow for off-interface Actors (eg, non-renderables under scenes, anything under sprites or systems)
* Simpler/more consistent handling of subsets of children (eg, sprites)

No, I don't know if I want to call it the Unified Tree Model, the Game Object Model, or something else. Suggestions welcome.

### PR DESCRIPTION
**Pull request by AstraLuma**
Implements a standard interface for "game objects" (things that participate in the tree and receive events)

Part of #492

### CODE REVIEW

**Comment by AstraLuma** [comment]
I did make a `FilteredView` but I haven't included it yet because we don't have a need.

**Comment by AstraLuma** [comment]
I'm deliberately leaving out the engine changes in this PR.

**Comment by pathunstrom** [comment]
Leaving a few comments here just to note the discussion:

* Subsprites and relative to parent positioning will be a valuable feature. We don't need to add it in the PR, so will open an issue once this one is merged.
* Adding a children kwarg to the GameObject init that can be passed to the Children would allow us to add objects on instantiation. Not a blocker, but a thing we should consider.

**Review by pathunstrom — APPROVED** [review]
This looks good, going to wait on bors until we're sure everything we want is here.

**Comment by AstraLuma** [comment]
Updated for camera.

**Review by pathunstrom — APPROVED** [review]
bors r+

**Pull request merged**
