### PR TITLE
Refactor Logging

### PR DESCRIPTION
**Pull request by astronouth7303**
Handle logging better.

This also includes a `LoggingMixin` that handles the (admittedly small) boiler plate of getting & caching a logger.

### CODE REVIEW

**Comment by astronouth7303** [comment]
I'm also considering Fixing `events.py` to use this? That will move the data currently logged at `game.events`.

**Comment by pathunstrom** [comment]
I like that idea, but do we want EventMixIn to inherit from LoggerMixIn?

**Comment by astronouth7303** [comment]
ummm.... not really. That sounds like "yeah, this is implicitly on all your objects forever", which isn't super great.

**Comment by astronouth7303** [comment]
Oh, and it wouldn't do the right thing on a mixin anyway, so nevermind!

**Pull request merged**
