### PR TITLE
Mechanized Release Process

### PR DESCRIPTION
**Pull request by astronouth7303**
Implements a mechanized release process. Under this, the release process would be:

1. Go to GitHub Release pages
2. Look at the diff since last version, compile changelog
3. On the GitHub site, create a tag/release with the changelog and any other release notes
4. Cirrus CI is responsible for building and uploading to PyPI and GitHub

Additionally, dev releases are uploaded to PyPI test every time `master` is updated.

Version numbers are no longer explicitly listed in the repo, instead being calculated based on the git tags.

This code is a pretty direct copy from https://github.com/gqlmod/gqlmod (which is in part based on code that @duckinator wrote).

@nbraud originally proposed this for PPB.

### CODE REVIEW

**Comment by astronouth7303** [comment]
Note that I don't really expect this to be merged. It's more along the lines of "demo then discuss".

**Comment by astronouth7303** [comment]
Ok, I'm going to leave the shuffling of artifacts around until we decide to actually do this.

**Comment by pathunstrom** [comment]
> Additionally, dev releases are uploaded to PyPI test every time master is updated.

Alright this is pretty much the thing that settles my doubts. It gives us a live preview of the build artifacts before we cut a release. If you and @nbraud are happy with this, I'm happy with it.

**Comment by astronouth7303** [comment]
Ok, CI is green.

Just need to add the API tokens, and this should be good.

**Comment by astronouth7303** [comment]
NVM. I can't log in as the bot because of Security:tm:, so the credentials will have to wait.

**Comment by astronouth7303** [comment]
Tokens are in place.

Tested uploads.

I think this is good.

**Comment by pathunstrom** [comment]
Off we go into the new world.

bors r+

**Comment by astronouth7303** [comment]
bors retry

**Comment by astronouth7303** [comment]
bors retry

**Pull request merged**
