### PR TITLE
Use the bork container for building

### PR DESCRIPTION
**Pull request by AstraLuma**
bork now has a container (https://github.com/duckinator/bork/issues/90)

Use that

### CODE REVIEW

**Comment by pathunstrom** [comment]
```
git fetch --tags
/tmp/scripts1e00167939cb6694d2c422acd208a007.sh: line 5: git: command not found
```

That's uh. . . worrying.

**Comment by AstraLuma** [comment]
Yup, bounced back to duckinator.

Even if we removed that git command, `setuptools-scm` still needs it for `git describe`.

**Comment by AstraLuma** [comment]
Ok, this looks like it's working now.

**Review by pathunstrom — APPROVED** [review]
bors r+

**Pull request merged**
