### PR TITLE
GOM: Update the event loop

### PR DESCRIPTION
**Pull request by AstraLuma**
Update the event loop to use the GOM

Part of #492

### CODE REVIEW

**Comment by pathunstrom** [comment]
So if I'm reading this correctly: This is a non-breaking change? Since end user code won't need to change at all to support this.

**Comment by AstraLuma** [comment]
Yeah, this only generalizes the tree and enables new tree shapes.

**Comment by pathunstrom** [comment]
Looks good.

bors r+

**Pull request merged**
