### PR TITLE
Animation framework

### PR DESCRIPTION
**Pull request by astronouth7303**
Basically:

```
class MySprite(BaseSprite):
    image = Animate('MySprite_{0..10}.png', 5)
```

### CODE REVIEW

**Comment by pathunstrom** [comment]
This leaves me wanting the file load API so we can move all the loading to the beginning.

But this looks promising. You want me to do the work in the renderer?

**Comment by astronouth7303** [comment]
I just did.

**Comment by astronouth7303** [comment]
Ok, I think this is ready to use. I still have to:

* [ ] Write tests
* [ ] Write docs

**Comment by astronouth7303** [comment]
Here's some test apps, making use of the Mutant Standard moon emoji
[moon.zip](https://github.com/ppb/pursuedpybear/files/3050072/moon.zip)

**Comment by astronouth7303** [comment]
Hm. The pause/unpause cycle causes frame skips.

**Comment by jamesBrosnahan** [comment]
Can the moon.zip file be added to examples?

**Comment by astronouth7303** [comment]
@jamesBrosnahan not as it is, due to the license on Mutant Standard.

**Comment by astronouth7303** [comment]
Ok, this is ready for review

**Comment by pathunstrom** [comment]
Tentative approval. I want to pull this and play with it a little way before giving the full green light. This shit is amazing, and the tests are clever.

**Comment by nbraud** [comment]
@astronouth7303 Would it be OK for things in `examples/` to depend on `ppb-mutant` for assets?
BTW, `ppb-mutant` doesn't currently specify a license.

**Pull request merged**
