### PR TITLE
Fixed a issue in viztest/main.py

### PR DESCRIPTION
**Pull request by abhijeetgupto**
Changed name from 'equilateral_tri'  to 'square_tri' !

### CODE REVIEW

**Comment by pathunstrom** [comment]
Primary feedback is we don't want to track the .replit file. Feel free to include it in the project .gitignore, and add your information to the CONTRIBUTORS file.

If you'd like to go above and beyond, you could rename the file from main.py to triangles.py or similar.

(Also, don't worry about that test failure, not your fault.)

**Comment by abhijeetgupto** [comment]
Thanks for the reply , this was my first commit ever . I'll try to improve .
Thanks!

> Primary feedback is we don't want to track the .replit file. Feel free to include it in the project .gitignore, and add your information to the CONTRIBUTORS file.
> 
> If you'd like to go above and beyond, you could rename the file from main.py to triangles.py or similar.
> 
> (Also, don't worry about that test failure, not your fault.)

**Comment by abhijeetgupto** [comment]
As instructed by you , I've change the file name to "triangles.py " and also added my information in CONTRIBUTORS.md .

**Review by pathunstrom — APPROVED** [review]
Looks good, thanks for the contribution!

bors r+

**Comment by pathunstrom** [comment]
Would you like to get a shoutout on Twitter from the pursuedpybear account?

**Comment by abhijeetgupto** [comment]
> Would you like to get a shoutout on Twitter from the pursuedpybear account?
Of course ! 
Thanks , I really appreciate that .

**Pull request merged**
