### PR TITLE
Adds show_cursor attribute to BaseScene to control cursor visibility.

### LINKED ISSUE #491: Add scene prop to hide cursor
Add a property to scenes to show/hide the cursor.

### PR DESCRIPTION
**Pull request by pathunstrom**
Resolves #491

### CODE REVIEW

**Review by AstraLuma — CHANGES_REQUESTED** [review]
I don't believe this will work with scene stacks (eg, a pause menu has a cursor but its parent doesn't).

**Comment by pathunstrom** [comment]
Oh, right, should do the check on SceneContinued too.

**Review by AstraLuma — APPROVED** [review]
bors r+

**Comment by AstraLuma** [comment]
bors retry

**Comment by pathunstrom** [comment]
bors retry

**Comment by pathunstrom** [comment]
bors retry

**Pull request merged**
