### PR TITLE
Next Generation Assets

### PR DESCRIPTION
**Pull request by astronouth7303**
Or: If assetlib is so good, why isn't there assetlib 2?

This refactors/rewrites many aspects of assetlib to simplify implementations and better enable future asset features. (#373)

### CODE REVIEW

**Comment by astronouth7303** [comment]
Ok, did a quick docs fixup (although the page needs a real pass).

I think this is ready for review.

**Comment by astronouth7303** [comment]
Umm... it really shouldn't be that noisy.

That warning that covers cases like #419, where someone tries to call `.load()` before the engine starts, which should result in deadlock.

Given that the lifespan of the executor should match the lifespan of the system, I'm not certain how this happened.

(I could, of course, refine the conditions in which the warning is given, but i'm still extremely puzzled as to why it happened.)

**Comment by pathunstrom** [comment]
My guess is that I define most of my assets at either the module level or the class attribute level, so when I import the first scene, it chains in basically everything else, and that happens before the engine starts?

**Comment by astronouth7303** [comment]
The warnings came from `FreeingMixin.__del__()` conflicting `BackgroundMixin.load()`'s warning. There isn't a real fix without a more specific combination.

Fixed by shushing if the asset is already loaded.

**Pull request merged**
