### PR TITLE
Adds doc-utils pin for read the docs.

### LINKED ISSUE #650: Docs builds are failing: Resolve by updating doc-utils requirement
A change was made to doc-utils to replace traversal with a generator. Sphinx tries to reverse the generator, which fails.

The current solution is to pin doc-utils in requirements-docs.txt to <0.18 as documented here: https://github.com/sphinx-doc/sphinx/issues/9727

### PR DESCRIPTION
**Pull request by pathunstrom**
Resolves #650

### CODE REVIEW

**Comment by AstraLuma** [comment]
Feel like there should be a comment about when to remove it?

**Comment by pathunstrom** [comment]
I mean, I don't know the answer to "when to remove it" I assume it's tied to when we update sphinx?

**Comment by AstraLuma** [comment]
That sounds like a good when.

It's a constraint tied to a bug, so just gotta make sure the next person knows that.

**Review by AstraLuma — APPROVED** [review]
bors r+

**Pull request merged**
