### PR TITLE
Switch docs theme to furo

### LINKED ISSUE #555: Switch docs theme to furo
#529 switched it from rtd to alabaster, and I'd rather we make a choice as official instead of up to whoever is working on the docs at the time.

Part of this may be hiring a designer to give us a basic identity for our websites that can be applied to ppb.dev and our docs websites.

If you have an opinion on what ppb should look for, here's where to get your voice in.

For the time being we aren't replacing Binny. I still quite like them.

### PR DESCRIPTION
**Pull request by jschwarzwalder**
Fixes #555

### CODE REVIEW

**Comment by pathunstrom** [comment]
Looks great, could you add a commit adding yourself to CONTRIBUTORS.md and we can merge this!

**Comment by pathunstrom** [comment]
Looks good!

bors r+

**Comment by pathunstrom** [comment]
bors retry

**Comment by AstraLuma** [comment]
bors try

**Comment by pathunstrom** [comment]
bors retry

**Pull request merged**
