### PR TITLE
Add a general contact for CoC problems

### PR DESCRIPTION
**Pull request by astronouth7303**
Based on the [advice of Sage](https://twitter.com/_sagesharp_/status/1131556027596361728).

### CODE REVIEW

**Comment by astronouth7303** [comment]
Also: @lunacodes are you ok taking on this responsibility?

**Comment by nbraud** [comment]
@pathunstrom Generally, it might also be useful to have a `maintainers@` alias (if there isn't one already) and point `codeofconduct@` at that (at least for now).

**Comment by nbraud** [comment]
bors r=nbraud,pathunstrom

**Comment by lunacodes** [comment]
> Also: @lunacodes are you ok taking on this responsibility?

I'm fine with taking that on. Thx for checking in!

**Pull request merged**
