### PR TITLE
Adds a CHANGELOG.txt

### PR DESCRIPTION
**Pull request by pathunstrom**
The goal of this is to have a place to put notes when we merge in new features, change existing features, and remove features. This includes the notes from every previous release to 0.2.0 (0.2.0 is the release that restarted the project.)

Going forward, the changelog can be modified separately from the features (to prevent too many merge conflicts with people modifying the changelog with their changes) and we should do that sometime after bors is finished cleaning up.

### CODE REVIEW

**Comment by astronouth7303** [comment]
I'm not super happy about "try to remember to update the changelog occasionally" as a process?

Also, is the changelog on the github releases page insufficient?

**Comment by pathunstrom** [comment]
Surfacing off github discussion:

The point of this is less that the changelogs attached to releases are insufficient, it's more I'm tired of going back and having to dig through and often missing features because it's not something I was considering.

The goal is that whoever merges a feature opens a new PR immediately (or soon after) including those notes in this file.

**Comment by astronouth7303** [comment]
Ok, to be clear:

Yes, compiling changelogs from commit or PR history is very annoying. It would be really nice if we could track changelog entries as we developed.

I'm not a fan of "remember to make a PR" as a process.

**Comment by pathunstrom** [comment]
Closing until we figure out a solution.

**Pull request closed without merging**
